### ISSUE TITLE
Open Source Request for NetGP Experiment Code on GraphCDR

### ISSUE THREAD

**Issue by Kimmm-pzl** [minwoopak/NetGP#1]
Hi,

I'm impressed by your work on NetGP. Would you be willing to open source the GraphCDR experiment code for NetGP? Your contribution would be greatly appreciated!

Thank you,
Kim

**Comment by minwoopak** [comment]
The performance comparison for GraphCDR was quite different from other models. 
First of all, GraphCDR does not handle regression problem. 
Secondly, the problem setting for GraphCDR is Transductive setting. Therefore, we compared the model with different metrics and the comparison could not be done for all the four data split settings suggested in the NetGP paper.
More importantly, the integration of the perturbation profile from NetGP into GraphCDR is also different as well. We first embeded the perturbation profile with an MLP model and concatenated the output vector with the original drug vector of GraphCDR. 
The experiment code is not cleaned and needs refactoring. If you still want the code for the model, please let me know your email address and I will send it to you personally.
The original code for GraphCDR is [here](https://github.com/BioMedicalBigDataMiningLab/GraphCDR).
The modified part is the `NodeRepresentation` class in 'GraphCDR/prog/model.py'.

**Comment by Kimmm-pzl** [comment]
Thank you for your reply! My email is 2366960753@qq.com.
